### ISSUE TITLE
Backend API

### ISSUE THREAD

**Issue by tekinc** [DenisKovalyonokSamples/DriverInsurance#2]
How could I test this with a backend?

**Comment by DenisKovalyonokSamples** [comment]
Hi, it's only Xamarin app sample. Backend API will not be included for public usage. You can write some stab data or add calls to your custom API. Thanks!

**Comment by tekinc** [comment]
Thanks offering the source. Is it possible to purchase the backend?

**Comment by DenisKovalyonokSamples** [comment]
Sorry, but it's not possible. Backend was made by another team. My responsibilities included only mobile applications development. Thanks.

**Comment by tekinc** [comment]
Thanks!
